import { StreamMessage, WorkflowNode, Agent, Connection } from '../App';
import { Card } from './ui/card';
import { Badge } from './ui/badge';
import { ArrowRight, Loader2, List, FileText, CheckCircle2, XCircle } from 'lucide-react';
import { ScrollArea } from './ui/scroll-area';

interface StreamingPanelProps {
  messages: StreamMessage[];
  nodes: WorkflowNode[];
  agents: Agent[];
  connections: Connection[];
}

export function StreamingPanel({ messages, nodes, agents, connections }: StreamingPanelProps) {
  const getAgentName = (nodeId: string) => {
    const node = nodes.find(n => n.id === nodeId);
    const agent = agents.find(a => a.id === node?.agentId);
    return agent?.name || 'Unknown';
  };

  const formatTimestamp = (timestamp: number) => {
    const date = new Date(timestamp);
    return date.toLocaleTimeString('en-US', { 
      hour: '2-digit', 
      minute: '2-digit',
      second: '2-digit' 
    });
  };

  // Separate outputs from regular messages
  const outputs = messages.filter(m => m.isOutput);
  const regularMessages = messages.filter(m => !m.isOutput);

  return (
    <div className="w-96 bg-white border-l border-slate-200 flex flex-col h-full">
      <div className="p-4 border-b border-slate-200 flex-shrink-0">
        <h3 className="text-slate-900 mb-1">Data Stream</h3>
        <p className="text-slate-600">Connection execution order</p>
      </div>

      <ScrollArea className="flex-1 h-full">
        <div className="p-4">
        
        {/* Workflow Outputs Section */}
        {outputs.length > 0 && (
          <div className="mb-6">
            <div className="flex items-center gap-2 mb-3">
              <FileText className="w-4 h-4 text-slate-600" />
              <h4 className="text-slate-900">Workflow Outputs</h4>
            </div>
            <div className="space-y-3">
              {outputs.map((output) => (
                <Card 
                  key={output.id} 
                  className={`p-4 border-2 ${
                    output.outputStatus === 'success' 
                      ? 'border-green-500 bg-green-50' 
                      : 'border-red-500 bg-red-50'
                  }`}
                >
                  <div className="flex items-center gap-2 mb-3">
                    {output.outputStatus === 'success' ? (
                      <CheckCircle2 className="w-5 h-5 text-green-600" />
                    ) : (
                      <XCircle className="w-5 h-5 text-red-600" />
                    )}
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <span className="text-slate-900">workflow_output{output.outputType}</span>
                        <Badge 
                          variant={output.outputStatus === 'success' ? 'default' : 'destructive'}
                          className="text-xs"
                        >
                          {output.outputStatus === 'success' ? 'Success' : 'Error'}
                        </Badge>
                      </div>
                      <p className="text-slate-600 mt-1">
                        Generated by {getAgentName(output.fromNodeId)}
                      </p>
                    </div>
                  </div>
                  
                  <div className="bg-white rounded p-3 mb-3 max-h-40 overflow-y-auto">
                    <p className="text-slate-700 whitespace-pre-wrap">
                      {output.content}
                    </p>
                  </div>
                  
                  <div className="flex items-center justify-between">
                    <span className="text-slate-500">
                      {formatTimestamp(output.timestamp)}
                    </span>
                    <Badge variant="outline" className="text-xs">
                      {output.outputType}
                    </Badge>
                  </div>
                </Card>
              ))}
            </div>
          </div>
        )}
        
        {/* Connection Order List */}
        {connections.length > 0 && (
          <div className="mb-6">
            <div className="flex items-center gap-2 mb-3">
              <List className="w-4 h-4 text-slate-600" />
              <h4 className="text-slate-900">Execution Order</h4>
            </div>
            <div className="space-y-2">
              {connections.map((connection, index) => {
                const sourceNode = nodes.find(n => n.id === connection.sourceId);
                const targetNode = nodes.find(n => n.id === connection.targetId);
                const sourceAgent = agents.find(a => a.id === sourceNode?.agentId);
                const targetAgent = agents.find(a => a.id === targetNode?.agentId);
                
                return (
                  <Card 
                    key={connection.id} 
                    className={`p-3 transition-all ${
                      connection.isActive 
                        ? 'border-l-4 border-l-blue-500 bg-blue-50' 
                        : 'border-l-4 border-l-slate-300'
                    }`}
                  >
                    <div className="flex items-center gap-2">
                      <div className="flex-shrink-0 w-6 h-6 rounded-full bg-slate-200 flex items-center justify-center">
                        <span className="text-slate-700">{index + 1}</span>
                      </div>
                      <div className="flex items-center gap-2 flex-1 min-w-0">
                        <span className="text-slate-900 truncate">
                          {sourceAgent?.name || 'Unknown'}
                        </span>
                        <ArrowRight className="w-3 h-3 text-slate-400 flex-shrink-0" />
                        <span className="text-slate-900 truncate">
                          {targetAgent?.name || 'Unknown'}
                        </span>
                      </div>
                      {connection.isActive && (
                        <Loader2 className="w-4 h-4 text-blue-500 animate-spin flex-shrink-0" />
                      )}
                    </div>
                  </Card>
                );
              })}
            </div>
          </div>
        )}

        {/* Messages Section */}
        {messages.length === 0 && connections.length === 0 ? (
          <div className="text-center py-12">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-full bg-slate-100 mb-4">
              <ArrowRight className="w-8 h-8 text-slate-400" />
            </div>
            <p className="text-slate-600">
              No connections yet
            </p>
            <p className="text-slate-500 mt-1">
              Add connections to build your workflow
            </p>
          </div>
        ) : messages.length > 0 ? (
          <div>
            <div className="flex items-center gap-2 mb-3">
              <h4 className="text-slate-900">Messages</h4>
              <Badge variant="secondary">{messages.length}</Badge>
            </div>
            <div className="space-y-3">
              {regularMessages.map((message) => (
                <Card key={message.id} className="p-4 border-l-4 border-l-green-500">
                  <div className="flex items-center gap-2 mb-2">
                    <Badge variant="outline" className="text-xs">
                      {getAgentName(message.fromNodeId)}
                    </Badge>
                    <ArrowRight className="w-3 h-3 text-slate-400" />
                    <Badge variant="outline" className="text-xs">
                      {getAgentName(message.toNodeId)}
                    </Badge>
                    {message.status === 'streaming' && (
                      <Loader2 className="w-3 h-3 text-green-500 animate-spin ml-auto" />
                    )}
                  </div>
                  
                  <p className="text-slate-700 mb-2 whitespace-pre-wrap line-clamp-4">
                    {message.content}
                  </p>
                  
                  <div className="flex items-center justify-between">
                    <span className="text-slate-500">
                      {formatTimestamp(message.timestamp)}
                    </span>
                    {message.status === 'complete' && (
                      <Badge variant="secondary" className="text-xs">
                        Delivered
                      </Badge>
                    )}
                  </div>
                </Card>
              ))}
            </div>
          </div>
        ) : null}
        </div>
      </ScrollArea>

      {connections.length > 0 && (
        <div className="p-4 border-t border-slate-200 bg-slate-50 flex-shrink-0">
          <div className="flex items-center justify-between">
            <span className="text-slate-600">Total Connections</span>
            <Badge>{connections.length}</Badge>
          </div>
        </div>
      )}
    </div>
  );
}